#!/usr/bin/env bash
# Conductor archive hook. Runs from the workspace directory just before the
# workspace is archived.
#
# This project creates nothing outside its workspace: no server, no port, no
# container, no database, no cloud state. The only useful work here is warning
# about work that is about to go out of view, and reclaiming the build state
# this workspace carries (node_modules alone is about 100 MB).
#
# Deliberately no "set -e", and it always exits 0: a cleanup hiccup must never
# block an archive.
set -uo pipefail

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

ca_say "Clean-Autofill archive hook: $CA_ROOT"

# Guard 1, the important one: refuse unless this is a LINKED git worktree.
# In the root checkout "git rev-parse --git-dir" and "--git-common-dir" return
# the same value; in a linked worktree they differ. This does not depend on any
# Conductor environment variable, so it also holds when the script is run by
# hand, and it makes cleaning the root checkout structurally impossible.
CA_GIT_DIR="$(git rev-parse --git-dir 2>/dev/null || echo '')"
CA_GIT_COMMON="$(git rev-parse --git-common-dir 2>/dev/null || echo '')"
if [ -z "$CA_GIT_DIR" ] || [ "$CA_GIT_DIR" = "$CA_GIT_COMMON" ]; then
  echo 'This is not a linked git worktree, so it may be the root checkout. Removing nothing.'
  exit 0
fi

# Guard 2: when Conductor tells us where the workspace is, it has to be here.
# Unset (cloud, or a manual run) falls through to guards 1 and 3.
if [ -n "${CONDUCTOR_WORKSPACE_PATH:-}" ]; then
  CA_WS="$(cd "$CONDUCTOR_WORKSPACE_PATH" 2>/dev/null && pwd -P || echo '')"
  if [ "$CA_WS" != "$CA_ROOT" ]; then
    echo 'CONDUCTOR_WORKSPACE_PATH does not point at this directory. Removing nothing.'
    exit 0
  fi
fi

# Guard 3: and it has to be this project.
if ! grep -q '"name": "clean-autofill"' "$CA_ROOT/package.json" 2>/dev/null; then
  echo 'This is not a Clean-Autofill checkout. Removing nothing.'
  exit 0
fi

# Surface work that is about to disappear from view. The branch itself survives
# archiving, this is only a reminder.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  echo ''
  echo 'Heads up, this workspace still has uncommitted changes:'
  git status --short 2>/dev/null | head -20
fi
CA_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
if git rev-parse --abbrev-ref '@{u}' >/dev/null 2>&1; then
  CA_UNPUSHED="$(git rev-list --count '@{u}..HEAD' 2>/dev/null || echo 0)"
  if [ "${CA_UNPUSHED:-0}" != "0" ]; then
    echo "Heads up, $CA_UNPUSHED commit(s) on $CA_BRANCH are not pushed."
  fi
else
  echo "Heads up, branch $CA_BRANCH has no upstream, so nothing on it has been pushed."
fi

if [ "${CLEAN_AUTOFILL_KEEP_BUILD_STATE:-0}" = "1" ]; then
  echo ''
  echo 'CLEAN_AUTOFILL_KEEP_BUILD_STATE=1, leaving node_modules/ and dist/ in place.'
  exit 0
fi

# Hard-coded allow list. Both entries are gitignored and fully regenerated by
# "bun install" plus "bun run build", and each one is re-checked below to be a
# real directory (not a symlink) that resolves inside this workspace. Nothing
# else can ever be removed, including a gitignored .env or credentials file.
echo ''
for CA_REL in node_modules dist; do
  CA_TARGET="$CA_ROOT/$CA_REL"
  [ -d "$CA_TARGET" ] || continue
  if [ -L "$CA_TARGET" ]; then
    ca_warn "$CA_REL is a symlink, refusing to remove it"
    continue
  fi
  CA_REAL="$(cd "$CA_TARGET" 2>/dev/null && pwd -P || echo '')"
  case "$CA_REAL" in
    "$CA_ROOT"/*) ;;
    *) ca_warn "$CA_REL does not resolve inside the workspace, refusing to remove it"; continue ;;
  esac
  CA_SIZE="$(du -sh "$CA_REAL" 2>/dev/null | cut -f1)"
  if rm -rf "$CA_REAL"; then
    echo "Removed $CA_REL (${CA_SIZE:-size unknown})"
  else
    ca_warn "could not remove $CA_REL"
  fi
done

echo ''
echo 'Archive cleanup done. Nothing outside this workspace was touched.'
echo 'Chrome keeps its own record of a loaded unpacked extension, so if this'
echo 'workspace was loaded there, remove the card at chrome://extensions.'
exit 0
